apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"

spec:
  project: default

  source:
    repoURL: https://github.com/GurkeSchaleSammler/homelab-helm.git
    targetRevision: main
    path: charts/cert-manager-config

    helm:
      valuesObject:
        acmeEmail: "rogerischback@outlook.com"

        cloudflare:
          secretName: cloudflare-api-token-secret

        dnsZones:
          - stoasis.ch
          - gurkeschale.ch

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true