apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/GurkeSchaleSammler/homelab-helm.git
    targetRevision: main
    path: charts/metallb-config

    helm:
      valuesObject:
        public:
          address: 192.168.0.240/32
          ipv6Address: 2a02:21b4:4a85:b800::240/128

        internal:
          address: 192.168.0.241/32
          ipv6Address: ""

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
