apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/GurkeSchaleSammler/homelab-helm.git
    targetRevision: main
    path: charts/metallb-config

    helm:
      valuesObject:
        public:
          address: 192.168.0.240/32

        internal:
          address: 192.168.0.241/32

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true