apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stoasis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/GurkeSchaleSammler/homelab-helm.git
    targetRevision: main
    path: charts/stoasis
    helm:
      releaseName: stoasis
      valuesObject:
        ingress:
          className: traefik-public
          clusterIssuer: letsencrypt-cloudflare
          frontend:
            host: app.stoasis.ch
          mcp:
            host: mcp.stoasis.ch
  destination:
    server: https://kubernetes.default.svc
    namespace: stoasis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
