apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-internal
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "41.5.0"

    helm:
      valuesObject:
        ingressClass:
          enabled: true
          isDefaultClass: false
          name: traefik-internal

        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik-internal
          kubernetesIngress:
            enabled: true
            ingressClass: traefik-internal

        service:
          type: LoadBalancer
          annotations:
            metallb.io/address-pool: internal-ingress
            metallb.io/loadBalancerIPs: 192.168.0.241
          spec:
            ipFamilyPolicy: SingleStack
            ipFamilies:
              - IPv4

        deployment:
          replicas: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-internal

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
